module ChatApp {
   interface ChatCallback {
      void callback(in string message);
      void update(in string message);
   };


   interface Chat {
      string say(in ChatCallback objref, in string message);
      string list(in ChatCallback objref);
      boolean join(in ChatCallback objref, in string user);
      void leave(in ChatCallback objref, in string user);
      string send(in ChatCallback objref, in string msg);
   };

interface ChatGame {
      void mark(in ChatCallback objref, in int x,in int y);
   };
};
