package ChatApp;


/**
* ChatApp/ChatPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* den 27 augusti 2015 kl 19:01 CEST
*/

public abstract class ChatPOA extends org.omg.PortableServer.Servant
 implements ChatApp.ChatOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("list", new java.lang.Integer (0));
    _methods.put ("join", new java.lang.Integer (1));
    _methods.put ("leave", new java.lang.Integer (2));
    _methods.put ("send", new java.lang.Integer (3));
    _methods.put ("mark", new java.lang.Integer (4));
    _methods.put ("playGame", new java.lang.Integer (5));
    _methods.put ("leaveGame", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ChatApp/Chat/list
       {
         ChatApp.ChatCallback objref = ChatApp.ChatCallbackHelper.read (in);
         String $result = null;
         $result = this.list (objref);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ChatApp/Chat/join
       {
         ChatApp.ChatCallback objref = ChatApp.ChatCallbackHelper.read (in);
         String user = in.read_string ();
         boolean $result = false;
         $result = this.join (objref, user);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // ChatApp/Chat/leave
       {
         ChatApp.ChatCallback objref = ChatApp.ChatCallbackHelper.read (in);
         String user = in.read_string ();
         this.leave (objref, user);
         out = $rh.createReply();
         break;
       }

       case 3:  // ChatApp/Chat/send
       {
         ChatApp.ChatCallback objref = ChatApp.ChatCallbackHelper.read (in);
         String msg = in.read_string ();
         this.send (objref, msg);
         out = $rh.createReply();
         break;
       }

       case 4:  // ChatApp/Chat/mark
       {
         ChatApp.ChatCallback objref = ChatApp.ChatCallbackHelper.read (in);
         short x = in.read_short ();
         short y = in.read_short ();
         short mark = in.read_short ();
         this.mark (objref, x, y, mark);
         out = $rh.createReply();
         break;
       }

       case 5:  // ChatApp/Chat/playGame
       {
         ChatApp.ChatCallback objref = ChatApp.ChatCallbackHelper.read (in);
         String userName = in.read_string ();
         this.playGame (objref, userName);
         out = $rh.createReply();
         break;
       }

       case 6:  // ChatApp/Chat/leaveGame
       {
         ChatApp.ChatCallback objref = ChatApp.ChatCallbackHelper.read (in);
         String userName = in.read_string ();
         this.leaveGame (objref, userName);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ChatApp/Chat:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Chat _this() 
  {
    return ChatHelper.narrow(
    super._this_object());
  }

  public Chat _this(org.omg.CORBA.ORB orb) 
  {
    return ChatHelper.narrow(
    super._this_object(orb));
  }


} // class ChatPOA
