package ChatApp;


/**
* ChatApp/ChatCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* den 27 augusti 2015 kl 19:01 CEST
*/

public interface ChatCallbackOperations 
{
  void update (String message);
  void announceWin (short x);
} // interface ChatCallbackOperations
