package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* den 26 augusti 2015 kl 0:29 CEST
*/

public interface ChatOperations 
{
  String list (ChatApp.ChatCallback objref);
  boolean join (ChatApp.ChatCallback objref, String user);
  void leave (ChatApp.ChatCallback objref, String user);
  void send (ChatApp.ChatCallback objref, String msg);
  void mark (ChatApp.ChatCallback objref, short x, short y, short mark);
  void playGame (ChatApp.ChatCallback objref, String userName);
  void leaveGame (ChatApp.ChatCallback objref, String userName);
} // interface ChatOperations
