package ChatApp;


/**
* ChatApp/Chat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* den 24 augusti 2015 kl 19:55 CEST
*/

public interface Chat extends ChatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Chat
